### ISSUE TITLE
Test case navigation does not work in Visual Studio 2017

### ISSUE THREAD

**Issue by nikolamilekic** [adamchester/expecto-adapter#12]
When you double click on a test case in the Test Explorer, Visual Studio 2015 navigates to that test case. This no longer works in 2017. Instead, the following error is shown on the status bar: "Cannot open the following file: [...]."

**Comment by adamchester** [comment]
Hey @nikolamilekic - It's actually working for me. Any chance you can dig a little deeper to find out what set of circumstances causes this? Are you using [4.0.0-alpha007](https://github.com/adamchester/expecto-adapter/releases/tag/4.0.0-alpha007)?

**Comment by nikolamilekic** [comment]
Sorry, I didn't get a chance to spend some time on this until now. I just tried again with an empty project and it's still not working. I also tried with xUnit and their runner and that didn't work either, so I'm calling it a problem with my machine or with Visual Studio.
