### ISSUE TITLE
It does not work :)

### ISSUE THREAD

**Issue by vasily-kirichenko** [adamchester/expecto-adapter#13]
![image](https://cloud.githubusercontent.com/assets/873919/24673772/17788db8-1982-11e7-8b69-0d93bed64c98.png)

Maybe it works on tests marked with attributes?

**Comment by ditadi** [comment]
Looking at the sample code (https://github.com/adamchester/expecto-adapter/blob/master/src/Expecto.Vstest.Console/Program.fs) it looks like the test function needs [<Tests>] attribute.

**Comment by vasily-kirichenko** [comment]
@ditadi Thanks! With that attribute applied the tests appear in the Text Explorer window and everything works great.
