### ISSUE TITLE
MissingMethodException Void ExpectoConfig..ctor(...)

### ISSUE THREAD

**Issue by jackfoxy** [adamchester/expecto-adapter#22]
When I attempt Run Selected Tests from VS 2015 test window (same in VS 2017, with Framework 4.6.1 and 4.7):

    System.MissingMethodException: Method not found: 'Void ExpectoConfig..ctor(Boolean, Int32, Microsoft.FSharp.Core.FSharpOption`1<System.TimeSpan>, System.TimeSpan, Double, Boolean, Microsoft.FSharp.Core.FSharpFunc`2<Expecto.Test,Expecto.Test>, TestPrinters, Expecto.Logging.LogLevel, Microsoft.FSharp.Core.FSharpFunc`2<Expecto.TestCode,Expecto.SourceLocation>, Int32, Int32, Microsoft.FSharp.Core.FSharpOption`1<Int32>)'.
    at Execution.ExecuteProxy.ExecuteTests()
    at Microsoft.FSharp.Control.AsyncBuilderImpl.commit[a](Result`1 res)
    at Microsoft.FSharp.Control.CancellationTokenOps.RunSynchronously[a](CancellationToken token, FSharpAsync`1 computation, FSharpOption`1 timeout)
    at Microsoft.FSharp.Control.FSharpAsync.RunSynchronously[T](FSharpAsync`1 computation, FSharpOption`1 timeout, FSharpOption`1 cancellationToken)
    at Execution.ExpectoTestExecutor.runAllExecutors()
    at Execution.ExpectoTestExecutor.Microsoft-VisualStudio-TestPlatform-ObjectModel-Adapter-ITestExecutor-RunTests(IEnumerable`1 tests, IRunContext runContext, IFrameworkHandle frameworkHandle)
   
Paket.lock:

    Expecto (5.0)
      Argu (>= 3.7)
      FSharp.Core (>= 4.1.12)
      Mono.Cecil (>= 0.10.0-beta5)
    Expecto.BenchmarkDotNet (5.0)
      BenchmarkDotNet (>= 0.10.5)
      Expecto (>= 5.0)
      FSharp.Core (>= 4.1.12)
    Expecto.FsCheck (5.0)
      Expecto (>= 5.0)
      FsCheck (>= 2.8)
      FSharp.Core (>= 4.1.12)
    Expecto.VisualStudio.TestAdapter (5.0.0-alpha008) - version_in_path: true
      Expecto (>= 5.0.0-beta1 < 6.0)
	  
    FSharp.Core (4.2.1)

**Comment by TeaDrivenDev** [comment]
Did you check the binding redirects for `FSharp.Core` in your test project? I don't think I've ever had MissingMethodExceptions in F# for any other reason.

**Comment by jackfoxy** [comment]
Just tried adding binding redirects. No difference. I'm now at .NET framework 4.7, so don't know if that would fix it at a lower version.

**Comment by MNie** [comment]
@jackfoxy 
Expecto.Adapter 5.0.0-alpha008 is not compatible with Expecto 5.0, information in [nuspec](https://www.nuget.org/packages/Expecto.VisualStudio.TestAdapter/) is incorrect:
![image](https://user-images.githubusercontent.com/7689103/27515232-0533b6ca-599f-11e7-915c-c5bdb57a4308.png)
It is compatible only with Expecto (>= 5.0.0-beta1 && <= 5.0.0-rc1). 
@adamchester  will release today a new version of adapter which should be compatible with Expecto (>= 5.0.0 && <= 6.0.0)

**Comment by MNie** [comment]
@jackfoxy new version of adapter is available on nuget.

**Comment by jackfoxy** [comment]
@MNie works as expected in VS 2017
