### ISSUE TITLE
No worky

### ISSUE THREAD

**Issue by o1lo01ol1o** [adamchester/expecto-adapter#32]
I have the tests annotated and the ``paket packages referenced in my project.  Running discover tests creates some noise on the output and ceases with:

```
[11/14/2017 2:26:04 PM Informational] ------ Discover test started ------
[11/14/2017 2:27:31 PM Error] 'vstest.discoveryengine.x86.exe' WCF communication channel unavailable. Active request will be aborted.
```

This is on VS 2017 15.4.4

**Comment by MNie** [comment]
@o1lo01ol1o I tried to reproduce your problem with 
```markdown
Microsoft Visual Studio Professional 2017 
Version 15.4.4
VisualStudio.15.Release/15.4.4+27004.2009
Microsoft .NET Framework
Version 4.7.02558

Installed Version: Professional
Visual F# 4.1   00369-60000-00001-AA048
Microsoft Visual F# 4.1
```
But everything seems to works fine.
![image](https://user-images.githubusercontent.com/7689103/33096921-ddca0d70-cf08-11e7-8d26-11e69c3f8cba.png)
