### ISSUE TITLE
5.0.1 missing on nuget

### ISSUE THREAD

**Issue by davidtme** [adamchester/expecto-adapter#33]
I looks like version 5.0.1 isn't on nuget

![image](https://user-images.githubusercontent.com/1804141/34052456-5de95060-e1ba-11e7-90ec-7c5b70226ed9.png)

**Comment by MNie** [comment]
Yup its still not available on nuget. @adamchester could you push a new version if you found some spare time :)?

**Comment by adamchester** [comment]
Sorry for delays, @MNie has the nuget permission now ;)

**Comment by MNie** [comment]
@adamchester #tactician I released a new version to [nuget](https://www.nuget.org/packages/Expecto.VisualStudio.TestAdapter/5.0.1)

**Comment by davidtme** [comment]
Thanks @adamchester and @MNie :)
