### ISSUE TITLE
Method not found: Void ExpectoConfig..ctor

### ISSUE THREAD

**Issue by jackfoxy** [adamchester/expecto-adapter#36]
Expecto.VisualStudio.TestAdapter 5.0.1
VS 2017 15.5.2

Test with https://github.com/jackfoxy/PersonalServer  master commit 36901bf 

Test window loads with tests successfully, but running any test throws:

````
System.MissingMethodException: Method not found: 'Void ExpectoConfig..ctor(Boolean, Int32, Microsoft.FSharp.Core.FSharpOption`1<System.TimeSpan>, System.TimeSpan, Double, Boolean, Microsoft.FSharp.Core.FSharpFunc`2<Expecto.Test,Expecto.Test>, TestPrinters, Expecto.Logging.LogLevel, Microsoft.FSharp.Core.FSharpFunc`2<Expecto.TestCode,Expecto.SourceLocation>, Int32, Int32, Microsoft.FSharp.Core.FSharpOption`1<Int32>, Boolean)'.
   at Execution.ExecuteProxy.ExecuteTests()
   at Execution.ExecuteProxy.ExecuteTests()
   at <StartupCode$Expecto-VisualStudio-TestAdapter>.$Execution.clo@180-10.Invoke(Unit unitVar)
   at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@841.Invoke(AsyncParams`1 args)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.FSharp.Control.AsyncBuilderImpl.commit[a](AsyncImplResult`1 res)
   at Microsoft.FSharp.Control.CancellationTokenOps.RunSynchronouslyInCurrentThread[a](CancellationToken token, FSharpAsync`1 computation)
   at Microsoft.FSharp.Control.CancellationTokenOps.RunSynchronously[a](CancellationToken token, FSharpAsync`1 computation, FSharpOption`1 timeout)
   at Microsoft.FSharp.Control.FSharpAsync.RunSynchronously[T](FSharpAsync`1 computation, FSharpOption`1 timeout, FSharpOption`1 cancellationToken)
   at Execution.ExpectoTestExecutor.runAllExecutors()
   at Execution.ExpectoTestExecutor.Microsoft-VisualStudio-TestPlatform-ObjectModel-Adapter-ITestExecutor-RunTests(IEnumerable`1 tests, IRunContext runContext, IFrameworkHandle frameworkHandle)
````

I think the problem might be a missing reference to ````Microsoft.VisualStudio.TestPlatform.ObjectModel 11.0.0.0````

**Comment by MNie** [comment]
Hi @jackfoxy, it is related to #34. When I return from holidays I will release a new version of adapter with fix'd nuspec and then take a Look at this issue.

**Comment by MNie** [comment]
@jackfoxy fix'd package pushed to nuget. I will take a look at the issue today/tomorrow.

**Comment by jackfoxy** [comment]
@MNie this is very weird, and has never happened before.
I did `paket update` to pick up the to pick up the 5.1.1 version, which I can see on nuget.org, and it did not update my paket.lock file.
OK, then I tried` paket update -f` same result.

Still investigating, but I will likely have to report this to Paket.

**Comment by MNie** [comment]
@jackfoxy indeed its weird. I also pushed a beta version of an adapter which is based on a new format of fsproj.

**Comment by jackfoxy** [comment]
@MNie  I think I found the problem.
The dependency in the nuspec file is 

\<dependency id="Expecto" version="[5.0.0, 5.1.1)" />

whereas Expecto has moved on to 5.1.2

**Comment by MNie** [comment]
@jackfoxy It is related to #34.
Also could you check if everything works fine for you with [6.0.0-alpha2](https://www.nuget.org/packages/Expecto.VisualStudio.TestAdapter/6.0.0-alpha2), if yes I would release it as a new package with version 6.0.0. I check it and it seems to works for me, no more error with ctor.

**Comment by jackfoxy** [comment]
Ah, so would be nice if Expecto respected semantic versioning. I'll checkout the alpha and let you know

**Comment by jackfoxy** [comment]
6.0.0-alph2 works, with the exception that 1 out of 156 tests failed in the adapter, but does not fail when run through Expecto as console app.

It's a little complex so I don't know how long it will take me to research, and I'm not even sure when I can get to it.

**Comment by MNie** [comment]
@jackfoxy so I will wait with making an official release till you check what is wrong. But this is very weird since the logic of discovering/running tests doesn't change..

**Comment by jackfoxy** [comment]
The test in question is faulty and was not marked to run in the console test runner.
This release of the adapter is good. @MNie

**Comment by MNie** [comment]
@jackfoxy Excellent information! I will release 6.0.0 later today.

**Comment by MNie** [comment]
6.0.0 released.
