### ISSUE TITLE
Unable to discover any tests

### ISSUE THREAD

**Issue by TAGC** [adamchester/expecto-adapter#41]
I'm experimenting with F#/Expecto and using Visual Studio as my IDE. I've created a test project that references Expecto and Expecto.VisualStudio.Adapter. It has a test case defined in it, but Visual Studio's test runner fails to pick it up.

The test project contains these files:

**MyCompany.Message.FSharp.Tests.fsproj**

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Tests.fs" />
    <Compile Include="Program.fs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Expecto" Version="7.0.0" />
    <PackageReference Include="Expecto.VisualStudio.TestAdapter" Version="8.0.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.6.2" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\MyCompany.Message.FSharp\MyCompany.Message.FSharp.fsproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Update="FSharp.Core" Version="4.3.4" />
  </ItemGroup>
</Project>
```

**Tests.fs**

```fsharp
module Tests

open MyCompany.Message
open Expecto

[<Tests>]
let tests = 
    testCase "message should return size of payload in bytes" <| fun () ->
        let message = create 0x1 [1uy; 2uy; 3uy]
        Expect.equal 3 (size message) "unexpected message size"
```

**Program.fs**

```fsharp
module Program = let [<EntryPoint>] main _ = 0
```

#### Environment

 - Windows 10 1709
 - dotnet v2.1.103
 - Visual Studio 15.6.4

**Comment by jackfoxy** [comment]
I am having a discovery problem in one of my solutions, but not the other. The difference I can see between the two is the failing solution has net461 projects.

Both solutions:
VS 15.6.7
Expecto 7.0.1
Expecto.VisualStudio.TestAdapter 8.0.0 version_in_path: true

This solution discovers tests successfuly:

-root
	-Solution.sln
	-packages/
	-src/Project1/Project1.proj
	-src/Project1/bin/Debug/net45
	-src/Project1/bin/Debug/net47/Project1.dll
	-src/Project1/bin/Debug/netstandard2.0
	-src/Project2/Project2.proj
	-src/Project2/bin/Debug/net45
	-src/Project2/bin/Debug/net47
	-src/Project2/bin/Debug/net47/Project2.dll
	-src/Project2/bin/Debug/netstandard2.0
	-tests/Test1/TestProj1.proj
	-tests/Test1/bin/Debug/net47/TestProj1.exe
	-tests/Test2/TestProj2.proj
	-tests/Test2/bin/Debug/net47/TestProj2.exe
	
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
This solution does not discover tests:

[5/6/2018 9:54:10 AM Informational] ------ Discover test started ------
[5/6/2018 9:54:11 AM Informational] ========== Discover test finished: 0 found (0:00:01.2701232) ==========

-root
	-Solution.sln
	-packages/
	-src/Project1/Project1.proj
	-src/Project1/bin/Debug/net461/Project1.dll
	...many other projects
	-tests/Test1/TestProj1.proj
	-tests/Test1/bin/Debug/net461/TestProj1.exe

**Comment by MNie** [comment]
@TAGC sorry for a late response! .Net core is not supported in expecto.adapter. If you want to use Expecto adapter which works under .net core check [this adapter](https://www.nuget.org/packages/YoloDev.Expecto.TestSdk/) also there is an easy option to create a test project (`via dotnet new`) which contains all packages which give you an ability of running Expecto tests by `dotnet test` [here](https://www.nuget.org/packages/Expecto.Template)

@jackfoxy I think your problem is a little bit different, tests are not discovered at all, or only discover for .net framework related projects?

**Comment by jackfoxy** [comment]
@MNie Tests are not discovered in the solution that only has net461 projects.
Tests ARE DISCOVERED in solutions that have netstandard2.0 among the targets, and the test projects themselves are net47. I'm not saying this is significant. That is just the environment information I am reporting.

**Comment by MNie** [comment]
@jackfoxy roger that I will take a look at this in a free time. I will also create an issue to add support to a .net core in an adapter.

**Comment by jackfoxy** [comment]
If you ever want to give me some pointers on setting up an adapter test environment, I may be able to file more informative issue reports, or even PRs.

**Comment by jackfoxy** [comment]
@MNie  Here's a commit that replicates the problem:
https://github.com/fsprojects/FSharpx.Collections/commit/e5a93c7176183fcfb8ca8bc71c2fa278a53c5814

Visual Studio 15.7.2
TestAdapter 9.0.0

Is it having issues with multi-targeted projects and/or net461?

````
No test is available in E:\GitRepos\FSharpx.Collections\docs\content\csharp\bin\Debug\csharp.exe
E:\GitRepos\FSharpx.Collections\src\FSharpx.Collections.Experimental\bin\Debug\net461\FSharpx.Collections.Experimental.dll
E:\GitRepos\FSharpx.Collections\src\FSharpx.Collections\bin\Debug\net461\FSharpx.Collections.dll
E:\GitRepos\FSharpx.Collections\tests\FSharpx.Collections.Experimental.Tests\bin\Debug\net47\FSharpx.Collections.Experimental.Tests.exe
E:\GitRepos\FSharpx.Collections\tests\FSharpx.Collections.Tests\bin\Debug\net47\FSharpx.Collections.Tests.exe.
Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.
````

**Comment by jackfoxy** [comment]
My BIG mistake here. For some projects I have test adapter in the paket.dependencies file, but not in the paket.referenes file of the unit test project. So not a problem for me after fixing that. 
I don't know if @TAGC still has a problem. 
From my perspective @MNie this can be closed.

**Comment by MNie** [comment]
@jackfoxy great to hear!
for @TAGC there is a separate issue for a support to .net core.
