### ISSUE TITLE
Support for Newtonsoft.Json 11 & 12

### ISSUE THREAD

**Issue by trbarrett** [adamchester/expecto-adapter#46]
```
Error Unable to resolve dependencies. 'Newtonsoft.Json 11.0.2' is not compatible with 'Expecto.VisualStudio.TestAdapter 10.0.1 constraint: Newtonsoft.Json (>= 10.0.0 && < 11.0.0)'.				
```

Hi, would it be possible to add support for more recent versions of Newtonsoft.Json to the nuget dependencies? 11.X, which came out last February, and perhaps the more recent 12.X?

https://github.com/adamchester/expecto-adapter/blob/master/nuspec/Expecto.VisualStudio.TestAdapter.nuspec#L22

https://github.com/JamesNK/Newtonsoft.Json/releases

Cheers

**Comment by jackfoxy** [comment]
Expecto.VisualStudio.TestAdapter 10.0.1, which requested package Newtonsoft.Json: >= 10.0 < 11.0
Fake.DotNet.Cli 5.0.0 requested package Newtonsoft.Json: >= 11.0.2
causing Fake to downgrade Expecto

**Comment by MNie** [comment]
I will try to update it during a weekend.

**Comment by MNie** [comment]
@adamchester could you push it to nuget since my apikey expired, please :)?

**Comment by adamchester** [comment]
@MNie sent you the code ;)

**Comment by MNie** [comment]
@jackfoxy, @trbarrett  pushed a new version.

**Comment by jackfoxy** [comment]
I just tested. Everything looks good. Thanks, @MNie
