### ISSUE TITLE
Tests do not show in test explorer when you attempt to reference the this nuget package using paket

### ISSUE THREAD

**Issue by chinwobble** [adamchester/expecto-adapter#8]
You need to use nuget package manager however most F# projects will want to use paket. 

Is it possible to make this not require nuget package manager?

**Comment by adamchester** [comment]
Hey @chinwobble.

Please try using the paket `version_in_path: true` setting on this.

https://fsprojects.github.io/Paket/nuget-dependencies.html#Putting-the-version-no-into-the-path

Sorry it's not obvious on the doco yet, PR would be welcome :)

**Comment by chinwobble** [comment]
@adamchester  thanks for the quick reply.
Yea putting that in the paket.dependencies file works. I meant that you still need to use a packages.config file and can't use a paket.references file in the project.

**Comment by chinwobble** [comment]
@adamchester  I'll have a go at trying to make a PR but have never done much with extensions before...

**Comment by adamchester** [comment]
I believe it's a limitation of the way visual studio handles test adapters.

**Comment by adamchester** [comment]
If you find any solution, please do share! 👍

**Comment by mgyongyosi** [comment]
As @adamchester said, it's a limitation of visual studio. If I'm right, Paket generates a packages.config file if you set the version_in_path: true and after that VS should discover your tests.

 They have the same issue with xUnit (https://github.com/fsprojects/Paket/issues/516),
